### ISSUE TITLE
[public report]: hyperlink doesn’t work correctly. 

### ISSUE THREAD

**Issue by antonyip** [MetricsDAO/xyz#610] opened 2023-03-23 01:07 UTC
### User Impacted

-

### Discord ID (including number)

-

### Workflow Impacted

Analyze

### Feature Impacted

Launch Challenge

### Issue description

I’m on this page. https://beta.metricsdao.xyz/app/market/0x280b3b748Ccc42D5062CE59111fAd08594f51d9F
clicked on this link. 
https://beta.metricsdao.xyz/app/analyze/m/0x280b3b748Ccc42D5062CE59111fAd08594f51d9F/sr/1
Expected to see something. 

### Blocking

yes it is

**Comment by ltirrell** [comment] 2023-03-23 04:28
Seems to be a mobile-only issue. i can reproduce using Brave on Android.

The second link from ant (https://beta.metricsdao.xyz/app/analyze/m/0x280b3b748Ccc42D5062CE59111fAd08594f51d9F/sr/1) doesn't work on desktop either. 

However, when going to the first (marketplace) link and clicking on the challenge, it goes to this page instead:
https://beta.metricsdao.xyz/app/market/0x280b3b748Ccc42D5062CE59111fAd08594f51d9F/request/1

**Comment by gnomadic** [comment] 2023-04-05 14:22
hey this should be fixed - odd request, but please don't use those old links :) we have an open bug with "phantom" labor markets resurfacing from our testing when they are visited directly via url.   We probably won't fix the issue tbh because it'll just go away once people stop opening direct links to old testing marketplaces.

**Closed by gnomadic** 2023-04-05 14:22 UTC
Labels: triage
