### ISSUE TITLE
[public report]: Brainstorm Private Marketplace Creation Application Error

### ISSUE THREAD

**Issue by PCWCFA** [MetricsDAO/xyz#367] opened 2023-02-10 19:31 UTC
### User Impacted

0xe95608B6a7f97bf5D076F0594EEe07e77b9781b7

### Discord ID (including number)

PCWCFA#0438

### Workflow Impacted

Brainstorm

### Feature Impacted

Create Marketplace

### Issue description

On a second attempt to create a private Brainstorm marketplace, encountered an Application Error on submission. See the attached. 

```
Application Error
Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1.2832781646007085e+48, code=NUMERIC_FAULT, version=bignumber/5.7.0)
    at _.makeError (https://dev.metricsdao.xyz/build/_shared/chunk-363DRRZZ.js:1:48020)
    at _.throwError (https://dev.metricsdao.xyz/build/_shared/chunk-363DRRZZ.js:1:48138)
    at nr (https://dev.metricsdao.xyz/build/_shared/chunk-363DRRZZ.js:1:56463)
    at L.from (https://dev.metricsdao.xyz/build/_shared/chunk-363DRRZZ.js:1:59390)
    at $ (https://dev.metricsdao.xyz/build/routes/app/$mType/new-VGCQPONY.js:1:8245)
    at K (https://dev.metricsdao.xyz/build/routes/app/$mType/new-VGCQPONY.js:1:8453)
    at Ki (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:5:52842)
    at bs (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:9:8687)
    at Zs (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:9:933)
    at Wf (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:9:864)
    at ot (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:9:724)
    at hi (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:7:10856)
    at https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:5:38670
    at L.unstable_runWithPriority (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:1:4059)
    at tn (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:5:38448)
    at Es (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:5:38616)
    at ge (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:5:38551)
    at Xf (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:9:6745)
    at L.unstable_runWithPriority (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:1:4059)
    at tn (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:5:38448)
    at Ye (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:9:6029)
    at https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:9:5943
    at ul (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:1:3089)
    at tl.port1.onmessage (https://dev.metricsdao.xyz/build/_shared/chunk-KD6LUU3Z.js:1:1693)
    

### Blocking

yes it is

### Relevant log output

_No response_

**Comment by elisemarika** [comment] 2023-02-13 20:43
@gnomadic any idea what that error means?

**Comment by gnomadic** [comment] 2023-02-14 00:06
@PCWCFA what kind of values are you putting in the rMetric fields?  

an overflow error is usually because a number is just too big - usually absurdly too big -

Can ya post a screenshot of what the form looks like?

**Comment by PCWCFA** [comment] 2023-02-14 02:54
I did not try to overflow the rewards field for day one of testing. I was using 5 for reward.

**Comment by gnomadic** [comment] 2023-02-14 15:10
haha I mean that's a good test we probably should do :)

Yeah that would've been too easy to troubleshoot this one.  I'm not sure where `1.2832781646007085e+48` is coming from, but that giant number is the problem.  Hate to say can ya try again?

**Comment by gnomadic** [comment] 2023-02-14 19:09
hey can you keep an eye out for this and report it again if it does come up?  If that does happen can you also post a screenshot of the form?  Appreciate it!

We're gonna close this one for now since we can't reproduce it and a lot has changed in the codebase over the last four days

**Closed by gnomadic** 2023-02-14 19:09 UTC
Labels: triage
