### ISSUE TITLE
Protocol layer - maxReviews on a Challenge

### ISSUE THREAD

**Issue by elisemarika** [MetricsDAO/xyz#633] opened 2023-04-03 15:35 UTC
**Job to be Done**
As a Sponsor, when launching a Challenge I want the ability to set a maximum reviews limit, so that I can more flexibly gate how many scores each submission can receive, and optimize my budgets and scoring needs in a way that best suits me

Requirements

Sponsors can optionally set a maximum reviews limit when launching a Challenge. limit = total scores across all challenges

**Comment by drakedanner** [comment] 2023-04-03 17:51
Curious if we need maxReviewers per Challenge or maxReviews per Submission

maxReviewers limits number of accounts that will need paid out so may handle the maxReviews as well?

Let us know if one is more impactful @masonchain or if you believe that maxReviewers handles the cross over nicely

**Comment by masonchain** [comment] 2023-04-03 21:09
Agree with @gnomadic's points above. @drakedanner I also think that the benefit of preventing situations where one submission received 12 reviews while another received one tips the scales alone.

**Comment by drakedanner** [comment] 2023-04-04 01:08
Great. Also agree on lopsided submissions concern, so we set a "Reviews per Submission" value. 

ie: I want 5 Reviews on each submission, my challenge solicits 20 submissions, n Reviewers can signal for a total of 100 reviews

Does this make sense?

**Comment by elisemarika** [comment] 2023-04-04 18:33
this all makes sense to me, maxReviews it is!

**Comment by drakedanner** [comment] 2023-04-05 18:06
maxReviews per requests allows us to have a situation where top items are reviewed more and spammy items are reviewed less.

In a way, this is more like "Avg Reviews per Submission" rather than "Max Reviews per Submission"

**Comment by drakedanner** [comment] 2023-04-05 18:12
> one benefit is, this was a simple request, and I only need 1 or 2 people from this reviewer network to validate its completion

Yeah!  I think we can still support that... Say we want 10 max submissions, and 1-2 reviews each, then we set Max Reviews to 15.

> setting a total review limit on the challenge could lead to some getting disproportionally more than others, and some none, when the intent is to validate easy work

Yes, this is the concern most obvious to me.

**Comment by elisemarika** [comment] 2023-04-05 18:15
@drakedanner the two are connected..if we say 15 max reviews, our network has no idea what our true intent is and maybe 3 submissions get 5 scores each and the rest of the submissions don't and we've failed

**Comment by masonchain** [comment] 2023-04-05 18:35
> Agree with @gnomadic's points above. @drakedanner I also think that the benefit of preventing situations where one submission received 12 reviews while another received one tips the scales alone.

After jumping in a call with Drake and Chance and discussing the uses for the maxes, I have to disagree with myself now.

The issue of evenly distributing reviews is really just us over-engineering the protocol in this case. The app should instead just suggest to a reviewer the submission that has the lowest amount of reviewers.

Chance started some documentation on how max reviews on a challenge fits into the system whereas max reviews per submission does not (he should be including it in this thread soon)

**Comment by nftchance** [comment] 2023-04-06 15:46
## Reviews interaction limits

We have been facing the problem where a Requester wants to incentivize a binary (or close to) action. While not binary in a transactional state, it is work that requires a low amount of oversight or quality assurance.

A simple stamp of approval will suffice.

The lack of a maximum cap on the provider side resulted in insufficient support for large-scale/high-volume marketplaces. Effectively, the growth of a market was parasitic to its future viability due to the ever-dropping return in payment. i.e., as more individuals participated, the payment for each went down respectively: their share of the pie.

To remedy this, we've implemented a "Request" wide limit that enables the ability to say, "If we don't reach 100% utilization, they will make more, but they will at least make ($pool/n$) in compensatory incentive.

This completely evaporates the baseline concern of token-held volatility while ensuring that the "health" and "relationship" of protocol:requester:provider was more easily upheld.

Contributing work, expecting payment, counting your chips, and that payment changing after the fact never feels good. A provider experiencing this is arguably a critical failure of the provider-economy structure.

In outcome, we have slated a Claim to submit limit with the function of:

> Challenge launcher can set a max claim to submit limit to limit how many analysts can claim a challenge to submit (control submission volume)

Critical to note, is the benefit focused: controlling submission volume.

Effectively, this results in a `CPA` metric Requesters can aim for while Providers and Reviewers unlock more operational transparency and power due to the ability to effectively determine if something sufficiently meets their compensation needs and wants.

Previously, projecting "earnings" was impossible due to the model implemented. That is no longer true due to the broad simplification and the max submission limit.

Following the road mapping of "submission limit," it makes logical sense to offer the same level on the reviewer side as the two economies are not diametrically opposing.

> This was the primary individual and organization complaint received from MetricsDAO about enforcement criteria, and this has been resolved and improved to offer a better experience to Labor Market providers!

## Controlling review assurance

Given the confirmed implementation of this functionality on the Provider side, it has been ideated to implement a similar Reviewer limit in form and function.

The currently proposed model is as follows: 

> - Challenge launcher can set a max reviews per individual submission limit to limit how many scores can be entered per submission (control review volume)

However, the above model, as highlighted by the above thread, would change that reality while introducing a significant amount of UX and prerequisite protocol knowledge to utilize the primitive, protocol and app fully.

Given this implementation, one would have to bifurcate the distinct functionality of `maximums` into:

* Providers have a global maximum limit.
* Reviewers have locally minimized maximum limit.

Given raw consumption, it would not be evident that the backing logic is different, nor does it benefit the economic model in any clearly advocated way.

Given the implementation of a "per submission limit," the mechanism would function as a lever to control the assurance one may have that a piece of work meets the criteria rather than the controlling factors that a "Provider Submission Limit" does.

Critically, it does not serve as a mechanism of volume control. 

Imagine the scenario:

- The requester configures for infinity submission claims.
- Reviewer pool is statically funded with $\$pToken$.
- 10 reviews per submission.

That means that as $N+1$ reviewers show up, the payment would continue decreasing effectively towards $\$0.00+dust$ without the protocol having any mechanism to control "decreased upside" (not technically feasible) as we cannot sort $O(n)$ lists onchain.

The result and implementation of this mechanism would result in an operator of Labor Markets being able to say: 

"We are ~(scaling cliff) sure that this submission is this ~(score) level of quality" -- creating a lever that allows operators to increase the level of quality assurance. 

That is not the overarching goal of the addition of `limits` though, as the sole focus of a `limit` is to control volume. The most effective `quality` and `criteria enforcement` levers held are `Badges used to gate participation` and `compensatory incentive.`

Labor Markets are already very complex conceptually, especially for new adopters. Therefore, it is best to unify the functionality of "maximum limits" across all labor economies rather than using shared terminology with conflated functionality behind the scenes.

> **Note**
> Hold this one at the top of your mind; limits were not designed to serve as a quality assurance lever but as volume.

## Controlling review volume

Interestingly, given the plan of #609 and #661, Providers have a more robust and transparent economy than ever before while finally securing the ability to offer a `CPA-like` system to the Requesters.

Because of all the reasons above, it is recommended that we proceed with #601 and #661 as planned while using #633 as the need for and implementation of a parallel experience to #601.

* Requesters need and deserve the ability to set a CPA for Reviewers.
* Reviewers deserve transparent pricing.

Critically, with this implementation, someone showing up and receiving disproportional payment is no longer unavoidable due to the combination of #661 and a more robust #620 now that final `problem clarity` has been acquired.

Therefore, maxReviews should be the maximum number of reviews that can be had on a Request and not based on `perSubmission.`

## FAQ

- **What about reaching 100% coverage of submissions being reviewed?**
- While controlling volume can assist in this, it cannot achieve it alone. Therefore, focusing on utilizing a more effective Reviewer market would be recommended, considering that insufficient capital (compensatory incentive) was provided and that more funds are needed to incentivize Reviewers to reach 100% sufficiently.

- **Can we prevent submissions from receiving $X < N < Y$ reviews?**
- No. The binding of submission reviews is ineffective and does not appropriately address "having scoring more sufficiently spread" rather than "preventing bad actors." Every piece of the protocol is designed to incentivize individuals to be good actors rather than obsessing over keeping someone from being a bad actor 

Notably, the web application **MAY** filter down and even automatically hide submissions at the application layer without needing to do so at the protocol layer adoption following the adoption of building with the Pareto principle.

Labor delivery and enforcement of quality is an activity bound to the social nuances of human collaboration, after all. For this reason, no technical implementation appropriately addresses this while we can provide a more significant incentive by adopting genuine `Provider Volume` --> the incentive is higher, more aligned, and more flexible in the hands of both the Requester and Provider.

Approved the above, "If there is a difference in the number of reviews, it may result in unfair outcomes." is no longer a large concern and can be managed with an established `CPA` when functioning with a genuine limit on both sides of the Provider and Reviewer economies.

**Comment by nftchance** [comment] 2023-05-04 21:44
Resolved in pending commit -- Will return with documentation and links.

**Closed** 2023-05-04 21:49 UTC
